[package]
name = "discord_selfbot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
poise = { git = "https://github.com/Kyza/poise", rev = "d270753", features = [
	"unstable",
] }
# serenity = { git = "https://github.com/jamesbt365/serenity", rev = "68cd033", features = [
# 	"unstable",
# ] }
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_plain = "1.0"
tokio = { version = "1.40", features = ["rt-multi-thread"] }
url = "2.5"
anyhow = "1.0"
byte-unit = "5.1"
tempfile = "3.13"
urlencoding = "2.1"
caith = { git = "https://github.com/Kyza/caith.git", rev = "fed75b3" }
chrono = "0.4"
chrono-tz = { version = "0.10", features = ["serde"] }
heck = "0.5"
indexmap = "2.6"
rand = "0.8"
tracing = "0.1"
syn = { version = "2.0.89", features = ["full"] }
regex = "1.11"
inline_format = "0.2"
rusty-tesseract = "1.1"
image = "0.25"
thirtyfour = "0.35"
fancy-regex = "0.14"
ron = "0.8"
phf = { version = "0.11", default-features = false, features = ["macros"] }
color-thief = "0.2"
# kalosm = { version = "0.3.2", features = ["vision", "cuda"] }
# ort-sys = "=2.0.0-rc.8"
# image = "0.24.7"
# cudarc = { version = "=0.12.1", features = ["cuda-version-from-build-system"] }
bon = "3.5"
mimalloc = "0.1"
favicon-picker = "1.1.0"
resvg = "0.45.1"
strum_macros = "0.27"
strum = "0.27"
