services:
   discord_selfbot:
      restart: always
      volumes:
         - type: bind
           source: ./config.ron
           target: /config.ron
         - ./assets:/assets
      build:
         context: .
         target: final
